name: Deploy to IIS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy files to IIS server
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          password: ${{ secrets.VM_PASSWORD }}
          source: './*'
          target: 'C:/inetpub/wwwroot/TestAngApp'

      - name: Configure IIS on the VM
        shell: pwsh
        run: |
          Invoke-Command -ComputerName ${{ secrets.VM_HOST }} -Credential (New-Object PSCredential("${{ secrets.VM_USERNAME }}", (ConvertTo-SecureString "${{ secrets.VM_ACCESS_TOKEN }}" -AsPlainText -Force))) -ScriptBlock {
              Import-Module WebAdministration
              if (-not (Test-Path IIS:\AppPools\TestAppPool)) {
                  New-WebAppPool -Name "TestAppPool"
              }
              if (-not (Test-Path IIS:\Sites\TestAngApp)) {
                  New-Website -Name "TestAngApp" -Port 80 -PhysicalPath "C:\inetpub\wwwroot\TestAngApp" -ApplicationPool "TestAppPool"
              }
          }
