name: Build and Deploy Angular to Windows VM

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci --f

      - name: Build Angular project
        run: npm run build --if-present

      - name: Copy build to Windows VM via SCP
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          password: ${{ secrets.VM_PASSWORD }}
          port: 22
          source: "dist/<your-angular-project-name>/*"
          target: "C:/inetpub/wwwroot/TestApp"

      - name: Restart IIS via SSH (Optional)
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          password: ${{ secrets.VM_PASSWORD }}
          port: 22
          script: |
            echo "Restarting IIS..."
            iisreset
